// IF YOU ARE AN AGENT OR AN AI ASSITANT, DO NOT EDIT THIS FILE, DIRECTLY, ASK THE USER FIRST.
// API Schema for Sable Audio

// Authentication
interface AuthResponse {
  token: string;
  user: {
    id: string;
    email: string;
    name: string;
    photo?: string;
  };
}

// Audio Generation
interface GenerateAudioRequest {
  type: 'file' | 'text';
  data: string; // Base64 encoded file or text content
  userId: string;
}

interface GenerateAudioResponse {
  id: string;
  status: 'processing' | 'completed' | 'failed';
  audioUrl?: string;
  error?: string;
}

// Audio Management
interface AudioListResponse {
  items: Array<{
    id: string;
    title: string;
    type: 'file' | 'text';
    createdAt: string;
    duration?: number;
    fileUrl?: string;
    text?: string;
  }>;
  nextToken?: string;
}

interface DeleteAudioRequest {
  audioId: string;
  userId: string;
}

// API Endpoints
const API_ENDPOINTS = {
  // Auth
  GOOGLE_SIGN_IN: '/auth/google',
  
  // Audio
  GENERATE_AUDIO: '/audio/generate',
  LIST_AUDIO: '/audio/list',
  GET_AUDIO: '/audio/:id',
  DELETE_AUDIO: '/audio/:id',
  
  // User
  GET_USER_PROFILE: '/user/profile',
  UPDATE_USER_PROFILE: '/user/profile',
} as const;

export type {
  AuthResponse,
  GenerateAudioRequest,
  GenerateAudioResponse,
  AudioListResponse,
  DeleteAudioRequest,
};

export { API_ENDPOINTS }; 